### ISSUE TITLE
PRÁCTICA1_RIGOBERTORAMIREZNICOLAS

### ISSUE THREAD

**Issue by Rmz-Rigo** [SistemasTecTlaxiaco/practica-architect-Rigoberto2001#1]
[DIAGRAMA_RIGOBERTORAMIREZNICOLAS.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-Rigoberto2001/files/7163550/DIAGRAMA_RIGOBERTORAMIREZNICOLAS.pdf)
[REPORTEDEPRACTICA_ARCHITECH_RIGOBERTORAMIREZNICOLAS.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-Rigoberto2001/files/7163551/REPORTEDEPRACTICA_ARCHITECH_RIGOBERTORAMIREZNICOLAS.pdf)

**Comment by Nayee123** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
esta bien hecho y revisado...
